<?php 
  use module\estate\helpers\RetsHtml;
?>
<div class="rets-view-block rets-detail-view">
    
    <div class="block-heading"><?php _t('rets', ' Property info')?></div>
    
    <?php foreach($detail as $group):?>
        <div class="detail-block">
            <div class="title"><?php _t('rets', $group['title'])?></div>
            <div class="body">
                <?php foreach($group['items'] as $item):?>
                    <?php echo RetsHtml::parseFieldHtml($item)?>
                <?php endforeach?>
            </div>
        </div>
    <?php endforeach?>
</div>

<style>
    .detail-block .title{margin-bottom:0;}
    body.estate-house-view .rets-detail-view .attr-field-expenses{width:100%;}
    .attr-field-expenses .attr-label{display:none}
    .attr-field-expenses .attr-value .expense {display: inline-block;width:50%;margin-bottom:5px;}
    .attr-field-expenses .attr-value .expense > label{font-weight:200;color:#777;}
    .attr-field-expenses .attr-value .expense > label:after{content:':';margin-right:10px;}
</style>